services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://dataBase:27017/myProjectDB
    depends_on:
      - dataBase
  
  dataBase:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db